import { DatabaseSync } from "node:sqlite";
import fs from "node:fs";
import path from "node:path";

/**
 * SQLite connection.
 *
 * Uses Node's built-in `node:sqlite` rather than the better-sqlite3 package.
 * better-sqlite3 is a native addon: on this machine (Node 23.4, Windows) npm
 * found no prebuilt binary and fell back to compiling from source, which needs
 * the Visual Studio C++ toolchain. Requiring a reviewer to install Visual
 * Studio to run a take-home is a worse trade than depending on a Node built-in,
 * and the first evaluation criterion is that it runs from a clean clone.
 *
 * The cost of that choice, stated plainly: `node:sqlite` needs Node 22.5 or
 * newer and still prints an ExperimentalWarning. The engines field in
 * package.json records the requirement.
 *
 * The database is a single file under data/. It is generated by
 * `npm run import` and is gitignored, so a clean clone runs the importer once
 * and has everything it needs - no database server, no migrations.
 */

export const DATA_DIRECTORY = path.join(process.cwd(), "data");
export const DATABASE_PATH = path.join(DATA_DIRECTORY, "adosx.sqlite");
const SCHEMA_PATH = path.join(process.cwd(), "lib", "schema.sql");

export type Db = DatabaseSync;

let cachedConnection: Db | null = null;

/**
 * Open (and memoise) the connection.
 *
 * Next.js reloads modules in development, so this is cached at module scope to
 * avoid piling up file handles on every hot reload.
 */
export function getDb(): Db {
  if (cachedConnection) return cachedConnection;

  if (!fs.existsSync(DATABASE_PATH)) {
    throw new Error(
      `No database at ${DATABASE_PATH}. Run \`npm run import\` first.`,
    );
  }

  // Note the capital O. `readonly` is not a recognised option and is silently
  // ignored, which hands back a writable connection that looks correct.
  cachedConnection = new DatabaseSync(DATABASE_PATH, { readOnly: true });
  return cachedConnection;
}

/**
 * Create a fresh, writable database with the schema applied, replacing any
 * existing file. Used only by the importer - a re-import is a full rebuild,
 * which keeps the importer simple and idempotent.
 */
export function createEmptyDb(): Db {
  fs.mkdirSync(DATA_DIRECTORY, { recursive: true });

  // WAL leaves sidecar files behind; clear them too so a rebuild really starts
  // from nothing.
  for (const suffix of ["", "-shm", "-wal"]) {
    const file = `${DATABASE_PATH}${suffix}`;
    if (fs.existsSync(file)) fs.rmSync(file);
  }

  const db = new DatabaseSync(DATABASE_PATH);
  // node:sqlite has no .pragma() helper, so pragmas go through exec().
  db.exec("PRAGMA journal_mode = WAL");
  db.exec(fs.readFileSync(SCHEMA_PATH, "utf8"));
  return db;
}

/**
 * Run `work` inside a transaction, rolling back if it throws.
 *
 * Written by hand because node:sqlite has no `.transaction()` wrapper of its
 * own. The importer relies on this: either the whole import lands or none of
 * it does, so a failure halfway through can never leave a half-populated
 * database that looks complete.
 */
export function runInTransaction<T>(db: Db, work: () => T): T {
  db.exec("BEGIN");
  try {
    const result = work();
    db.exec("COMMIT");
    return result;
  } catch (error) {
    db.exec("ROLLBACK");
    throw error;
  }
}
